### ISSUE TITLE
Breaks on malformed input

### ISSUE THREAD

**Issue by Shahor** [Teamwork/websocket-json-stream#4]
Hello, 

I am exploring using your package to replace the fork source we've been using for a while because it doesn't handle JSON parsing properly.

Although bad messages are caught, an error seems to be triggered a little bit further down the road in the readyState state machine. 

I am using this package in conjunction with ShareDB (works without issues on properly formatted messages).

My server code boils down to this:

```js
const wss = new WebSocketServer({
    server: server,
    path: 'some/path',
    verifyClient: (info, done) => done(true)
  })

  wss.on('connection', ws => {
    const stream = new WebSocketJSONStream(ws)

    sharedbConnection.listen(stream, ws.upgradeReq)
  })
```

And I send messages with this:

```js
const WebSocket = require('ws')

const socket = new WebSocket(
  'ws://localhost/some/path'
)

socket.on('open', function() {
  socket.send(Buffer.from([5]))
})
```

And here's the error I obtain:

![image](https://user-images.githubusercontent.com/204561/61386641-eb7e1880-a8b4-11e9-9851-175089d5cc9d.png)

It looks like the `this` context is lost in some call.

**Comment by Shahor** [comment]
It actually happens as well with the example provided in the repository:

![image](https://user-images.githubusercontent.com/204561/61387027-9a225900-a8b5-11e9-9b10-a4d614d4b3fc.png)

**Comment by gkubisa** [comment]
Strange, sending invalid data works properly for me. Which version of nodejs are you using? Could you also confirm that you're using @teamwork/websocket-json-stream at version 2.0.0.

**Comment by Shahor** [comment]
My version is specified in my prompt, last information in green after `via` keyword.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/204561/62045761-81e00180-b206-11e9-847d-cc6453ad8349.png">

**Comment by Shahor** [comment]
I can't reproduce the error I had with the example for some reason 🤔 

That being said, I still have the issue in the original process I use.

This process is ran in a docker container (not that it should be a factor, but in case), using the image `FROM node:10.15.2`

So:
- node version is 10.15.2
- ws@7.1.0
- @teamwork/websocket-json-stream@2.0.0

Full obtained stack trace is:

```
An uncaught exception just occured SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at WebSocketJSONStream.ws.addEventListener (/tmp/node_modules/@teamwork/websocket-json-stream/index.js:28:30)
    at WebSocket.onMessage (/tmp/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:194:15)
    at WebSocket.EventEmitter.emit (domain.js:441:20)
    at Receiver.receiverOnMessage (/tmp/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:189:13)
    at Receiver.EventEmitter.emit (domain.js:441:20)
    at Receiver.dataMessage (/tmp/node_modules/ws/lib/receiver.js:413:14)
    at Receiver.getData (/tmp/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/tmp/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (/tmp/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Receiver.Writable.write (_stream_writable.js:294:11)
    at Socket.socketOnData (/tmp/node_modules/ws/lib/websocket.js:875:35)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
```

**Comment by Shahor** [comment]
I'm sorry, I don't seem to be able to reproduce the issue, weirdly 🤔 

I'm closing this and will re-open if I face it again.
Thanks for your time!

**Comment by gkubisa** [comment]
Great, I'm glad it works. :-)
